CC	     = cc
CFLAGS	     = -g -O -I. -W -Wall
PICFLAGS     = -fPIC
LDFLAGS      =

HOST_CC      = cc
HOST_CFLAGS  = -g -O -I. -W -Wall
HOST_LDFLAGS =
HOST_LIBS    =

PERL         = time perl

#
# These are the files produced by convert_ucd.pl
#
CVT_FILES = gen/jamo.c gen/nameslist.tab gen/nametoucs.keys gen/nametoucs.tab \
	gen/ucstoname.keys gen/proparray.c gen/proparrayindex

# -----------------------------------------------------------------------

.SUFFIXES: .c .o .lo .s .ls .i .ho .hs .hi .cc .h
.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<
.c.lo:
	$(CC) $(CFLAGS) $(PICFLAGS) -c -o $@ $<
.c.s:
	$(CC) $(CFLAGS) -S -o $@ $<
.c.ls:
	$(CC) $(CFLAGS) $(PICFLAGS) -S -o $@ $<
.c.i:
	$(CC) $(CFLAGS) -E -o $@ $<
.c.ho:
	$(HOST_CC) $(HOST_CFLAGS) -c -o $@ $<
.c.hs:
	$(HOST_CC) $(HOST_CFLAGS) -S -o $@ $<
.c.hi:
	$(HOST_CC) $(HOST_CFLAGS) -E -o $@ $<

# -----------------------------------------------------------------------

LIBSRC = proparray.c gen/nametoucs_hash.c gen/ucstoname_hash.c \
	 gen/jamo.c gen/nameslist.c gen/nameslist_dict.c \
	 gen/ucstoname_tab.c

LIBOBJ = $(patsubst %.c,%.o,$(LIBSRC))
SO_OBJ = $(patsubst %.c,%.lo,$(LIBSRC))

# -----------------------------------------------------------------------

all : $(LIBOBJ) $(SO_OBJ)

clean:
	rm -rf gen
	rm -f *.o *.i *.*.a *.so *.so.*
	$(MAKE) -C perfect clean

# -----------------------------------------------------------------------

$(CVT_FILES) : gen/done

gen/done: convert_ucd.pl $(wildcard ucd/*.txt ucd/extracted/*.txt)
	mkdir -p gen
	$(PERL) convert_ucd.pl
	touch gen/done

perfect/perfect: $(wildcard perfect/*.c perfect/*.h)
	$(MAKE) -C perfect

gen/nametoucs_hash.c: gen/nametoucs.keys perfect/perfect
	perfect/perfect -im _libucd_nametoucs_hash gen/nametoucs_hash.c \
		gen/nametoucs_hash.h < gen/nametoucs.keys 

gen/nametoucs_hash.h: gen/nametoucs_hash.c
	: Generated by side effect

gen/ucstoname_hash.c: gen/ucstoname.keys perfect/perfect
	perfect/perfect -hm _libucd_ucstoname_hash gen/ucstoname_hash.c \
		gen/ucstoname_hash.h < gen/ucstoname.keys 

gen/ucstoname_hash.h: gen/ucstoname_hash.c
	: Generated by side effect

gen/nameslist.compr: gen/nameslist.tab simplecomp.pl
	$(PERL) simplecomp.pl < $<

gen/nameslist_tab.c gen/nameslist.offset: gen/nameslist.compr
	: Generated by side effect

gen/nameslist.c: gen/nameslist.compr bin2c.pl
	$(PERL) bin2c.pl _libucd_names_list < $< > $@ || rm -f $@

gen/mk_ucstoname_tab: mk_ucstoname_tab.ho gen/ucstoname_hash.ho
	$(HOST_CC) $(HOST_LDFLAGS) -o $@ $^ $(HOST_LIBS)

gen/ucstoname_tab.c: gen/mk_ucstoname_tab \
		     gen/proparrayindex gen/nameslist.offset
	gen/mk_ucstoname_tab

# -----------------------------------------------------------------------

proparray.o: proparray.c ucd.h libucd_int.h gen/proparray.c
proparray.lo: proparray.c ucd.h libucd_int.h gen/proparray.c

mk_ucstoname_tab.ho: gen/ucstoname_hash.h

gen/ucstoname_tab.o: gen/ucstoname_tab.c libucd_int.h
gen/ucstoname_tab.lo: gen/ucstoname_tab.c libucd_int.h

gen/nameslist_dict.o: gen/nameslist_dict.c
gen/nameslist_dict.lo: gen/nameslist_dict.c
